# .github/workflows/pr-check.yml
name: pr-check

on:
  pull_request:
    types:
      - opened

jobs:
  check_semver_labels:
    runs-on: ubuntu-latest
    name: A job to check the Semver labels exist on PR
    steps:
    - name: Check PR Labels
      uses: paul1k/check-pr-labels@v1.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pull-number: ${{ github.event.pull_request.number }}
        labels: '["major", "minor", "patch"]'
    - name: See result
      run: echo "${{ steps.check_pr_labels.outputs.result }}"
